name: Docker Build & Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:  # Optional: Enable manual runs

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/faster-whisper-api:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/faster-whisper-api:latest
